In [4]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
X_shapes = np.array([
    [4, 1.0], [4, 1.05], [4, 0.95], 
    [0, 1.0], [0, 1.1], [0, 0.9],   
    [4, 0.5], [0, 2.0]  
])
y_shapes = np.array([0, 0, 0, 1, 1, 1, 0, 1])
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_shapes, y_shapes, test_size=0.3, random_state=42
)
print("Shape Classification Data (X_train_s):\n", X_train_s)
print("\nShape Target (y_train_s):\n", y_train_s)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_s)
X_test_scaled = scaler.transform(X_test_s)
mlp = MLPClassifier(
    hidden_layer_sizes=(5,), 
    max_iter=2000,
    random_state=42,
    solver='adam'
)
mlp.fit(X_train_scaled, y_train_s)
y_pred_s = mlp.predict(X_test_scaled)
accuracy_s = accuracy_score(y_test_s, y_pred_s)
print("\nPredictions on X_test_s:\n", y_pred_s)
print("\nActual Shape Labels:\n", y_test_s)
print("\nMLP Classifier Accuracy:", round(accuracy_s, 2))


Shape Classification Data (X_train_s):
 [[0.   2.  ]
 [4.   0.95]
 [0.   1.1 ]
 [0.   1.  ]
 [4.   0.5 ]]

Shape Target (y_train_s):
 [1 0 1 1 0]

Predictions on X_test_s:
 [0 1 0]

Actual Shape Labels:
 [0 1 0]

MLP Classifier Accuracy: 1.0
